### ISSUE TITLE
Hey can we expect macro functionality?

### ISSUE THREAD

**Issue by cgokulc** [thekhalifa/m8mouse#2]
Firrst of all thanks for open sourcing, the driver. I am using a Readgear A-15 mouse based of same philip chip, so your driver works, there are other functionalities like button customization and macros. Can we expect those features? Are you still developing?

**Comment by thekhalifa** [comment]
Thanks for reporting that it worked with Redgear.
No plans on adding macros or key reassignment support as those wouldn't be very friendly through a command line config where you have to specify key sequences and it's more commonly a one time setup.
